name: Build and Release

on:
  push:
    tags:
      - "vNest*"
    branches:
      - "**"
    paths:
      - "GFLH-NestReroll/src/**"
      - "GFLH-NestReroll/mk/**"
      - ".github/workflows/**"
  pull_request:
    branches:
      - "**"
    paths:
      - "GFLH-NestReroll/src/**"
      - "GFLH-NestReroll/mk/**"
      - ".github/workflows/**"
  workflow_dispatch:

# Set global permission to read-only
permissions:
  contents: read

jobs:
  build:
    name: Build Windows x86_64
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Set up Python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r GFLH-NestReroll/mk/requirements.txt

      - name: Build with PyInstaller
        shell: bash
        run: python GFLH-NestReroll/mk/build_reroll.py

      - name: Prepare Artifact
        shell: bash
        run: |
              mkdir -p upload_stage
              cp -r "GFLH-NestReroll/dist/GFLH-NESTReroll" "upload_stage/GFLH-NestReroll-win-x86_64"

      - name: Upload Artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        with:
          name: "GFLH-NestReroll-win-x86_64"
          path: upload_stage

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/vNest')
    runs-on: ubuntu-latest
    # Only grant write permission to the specific job that needs to create a release
    permissions:
      contents: write
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3
        with:
          path: artifacts

      - name: Zip Artifacts
        run: |
          mkdir -p release_assets
          cd artifacts
          for dir in */; do
            dir=${dir%*/}
            zip_name="${dir}.zip"
            (cd "$dir" && zip -r "../../release_assets/$zip_name" .)
          done

      - name: Create Release
        uses: softprops/action-gh-release@01570a1f39cb16869b2ab4ef6583eb0b47fc47f7
        with:
          files: release_assets/*
          draft: false
          prerelease: false
          generate_release_notes: true
